### ISSUE TITLE
请求适配半次元

### ISSUE THREAD

**Issue by railyyyyy** [fankes/AndroidNotifyIconAdapt#257]
### APP 名称

半次元

### APP 包名

com.banciyuan.bcywebview

### 通知图标颜色 (HEX)

#FA4C8B

### 下载渠道、来源地址链接

https://www.bcy.net/

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
